[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Failover"
authors = [{name = "Paul Wekesa", email = "graziella@lumache"}]
dynamic = ["version", "description"]
urls.Source = "https://github.com/Paul-weqe/failover"
